main.py:10 #INFO     [2025-01-02 18:17:59,892] - config.logger - Starting bot
client.py:15 #INFO     [2025-01-02 18:18:04,006] - config.logger - Successfully connected to the SQLite database!
dispatcher.py:527 #INFO     [2025-01-02 18:18:04,187] - aiogram.dispatcher - Start polling
dispatcher.py:341 #INFO     [2025-01-02 18:18:04,346] - aiogram.dispatcher - Run polling for bot @free_listening_marathon_bot id=7531140107 - 'FREE LISTENING MARATHON'
subscription.py:30 #INFO     [2025-01-02 18:18:07,351] - config.logger - USER: 1856563190, Azizbek Qodirov
subscription.py:50 #WARNING  [2025-01-02 18:18:07,904] - config.logger - Error checking channel jasurbekisaev: Telegram server says - Bad Request: member list is inaccessible
dispatcher.py:172 #INFO     [2025-01-02 18:18:08,136] - aiogram.event - Update id=475191428 is not handled. Duration 785 ms by bot id=7531140107
dispatcher.py:315 #ERROR    [2025-01-02 18:18:08,136] - aiogram.event - Cause exception while process update id=475191428 by bot id=7531140107
TelegramBadRequest: Telegram server says - Bad Request: wrong file identifier/HTTP URL specified
Traceback (most recent call last):
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/free-course3/src/middleware/subscription.py", line 90, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/free-course3/src/handlers/start.py", line 59, in bot_start
    await message.answer_photo(photo=msg.photo_id, caption=msg.text_1, parse_mode=ParseMode.HTML)
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: wrong file identifier/HTTP URL specified
subscription.py:30 #INFO     [2025-01-02 18:18:21,810] - config.logger - USER: 1856563190, Azizbek Qodirov
subscription.py:88 #CRITICAL [2025-01-02 18:18:21,810] - config.logger - Error in SubscriptionMiddleware: 'NoneType' object has no attribute 'startswith'
start.py:65 #INFO     [2025-01-02 18:18:21,810] - config.logger - Photo ID: AgACAgIAAxkBAAMEZ3aSHeq5uxw_50q2oVab1u7CbeQAAl7nMRvMHLFLnDZ68cwn7D4BAAMCAAN5AAM2BA
dispatcher.py:172 #INFO     [2025-01-02 18:18:21,810] - aiogram.event - Update id=475191429 is handled. Duration 2 ms by bot id=7531140107
dispatcher.py:455 #WARNING  [2025-01-02 18:18:50,925] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:359 #INFO     [2025-01-02 18:18:50,925] - aiogram.dispatcher - Polling stopped for bot @free_listening_marathon_bot id=7531140107 - 'FREE LISTENING MARATHON'
dispatcher.py:554 #INFO     [2025-01-02 18:18:50,926] - aiogram.dispatcher - Polling stopped
client.py:22 #INFO     [2025-01-02 18:18:51,177] - config.logger - Connection to SQLite closed!
main.py:10 #INFO     [2025-01-02 18:18:53,164] - config.logger - Starting bot
client.py:15 #INFO     [2025-01-02 18:18:53,978] - config.logger - Successfully connected to the SQLite database!
client.py:45 #ERROR    [2025-01-02 18:18:53,979] - config.logger - SQLite error: table users already exists
dispatcher.py:527 #INFO     [2025-01-02 18:18:54,126] - aiogram.dispatcher - Start polling
dispatcher.py:341 #INFO     [2025-01-02 18:18:54,329] - aiogram.dispatcher - Run polling for bot @free_listening_marathon_bot id=7531140107 - 'FREE LISTENING MARATHON'
subscription.py:30 #INFO     [2025-01-02 18:19:00,354] - config.logger - USER: 1856563190, Azizbek Qodirov
subscription.py:50 #WARNING  [2025-01-02 18:19:00,884] - config.logger - Error checking channel jasurbekisaev: Telegram server says - Bad Request: member list is inaccessible
dispatcher.py:172 #INFO     [2025-01-02 18:19:01,363] - aiogram.event - Update id=475191430 is handled. Duration 1009 ms by bot id=7531140107
subscription.py:30 #INFO     [2025-01-02 18:19:26,937] - config.logger - USER: 1856563190, Azizbek Qodirov
subscription.py:50 #WARNING  [2025-01-02 18:19:27,628] - config.logger - Error checking channel jasurbekisaev: Telegram server says - Bad Request: member list is inaccessible
dispatcher.py:172 #INFO     [2025-01-02 18:19:28,302] - aiogram.event - Update id=475191431 is handled. Duration 1367 ms by bot id=7531140107
subscription.py:30 #INFO     [2025-01-02 18:19:29,599] - config.logger - USER: 1856563190, Azizbek Qodirov
subscription.py:50 #WARNING  [2025-01-02 18:19:29,936] - config.logger - Error checking channel jasurbekisaev: Telegram server says - Bad Request: member list is inaccessible
dispatcher.py:172 #INFO     [2025-01-02 18:19:30,351] - aiogram.event - Update id=475191432 is handled. Duration 753 ms by bot id=7531140107
dispatcher.py:172 #INFO     [2025-01-02 18:19:31,982] - aiogram.event - Update id=475191433 is handled. Duration 334 ms by bot id=7531140107
subscription.py:30 #INFO     [2025-01-02 18:20:10,866] - config.logger - USER: 1856563190, Azizbek Qodirov
subscription.py:50 #WARNING  [2025-01-02 18:20:11,362] - config.logger - Error checking channel jasurbekisaev: Telegram server says - Bad Request: member list is inaccessible
dispatcher.py:172 #INFO     [2025-01-02 18:20:12,041] - aiogram.event - Update id=475191434 is handled. Duration 1176 ms by bot id=7531140107
dispatcher.py:455 #WARNING  [2025-01-02 18:30:49,352] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:359 #INFO     [2025-01-02 18:30:49,353] - aiogram.dispatcher - Polling stopped for bot @free_listening_marathon_bot id=7531140107 - 'FREE LISTENING MARATHON'
dispatcher.py:554 #INFO     [2025-01-02 18:30:49,354] - aiogram.dispatcher - Polling stopped
client.py:22 #INFO     [2025-01-02 18:30:49,605] - config.logger - Connection to SQLite closed!
main.py:10 #INFO     [2025-01-02 18:30:51,389] - config.logger - Starting bot
client.py:15 #INFO     [2025-01-02 18:30:52,117] - config.logger - Successfully connected to the SQLite database!
client.py:45 #ERROR    [2025-01-02 18:30:52,117] - config.logger - SQLite error: table users already exists
dispatcher.py:527 #INFO     [2025-01-02 18:30:52,283] - aiogram.dispatcher - Start polling
dispatcher.py:341 #INFO     [2025-01-02 18:30:52,461] - aiogram.dispatcher - Run polling for bot @free_listening_marathon_bot id=7531140107 - 'FREE LISTENING MARATHON'
subscription.py:30 #INFO     [2025-01-02 18:30:54,423] - config.logger - USER: 1856563190, Azizbek Qodirov
subscription.py:50 #WARNING  [2025-01-02 18:30:54,946] - config.logger - Error checking channel jasurbekisaev: Telegram server says - Bad Request: member list is inaccessible
dispatcher.py:172 #INFO     [2025-01-02 18:30:55,096] - aiogram.event - Update id=475191435 is not handled. Duration 673 ms by bot id=7531140107
dispatcher.py:315 #ERROR    [2025-01-02 18:30:55,096] - aiogram.event - Cause exception while process update id=475191435 by bot id=7531140107
TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "b<asl" at byte offset 100
Traceback (most recent call last):
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/free-course3/src/middleware/subscription.py", line 90, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/free-course3/src/handlers/menu.py", line 25, in starty_link_handler
    await message.answer_photo(photo=msg.photo_id, caption=msg.text_1, parse_mode=ParseMode.HTML)
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/client/bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/azizbek/py-projects/num_converter/venv/lib/python3.12/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Unsupported start tag "b<asl" at byte offset 100
dispatcher.py:455 #WARNING  [2025-01-02 18:31:30,147] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:359 #INFO     [2025-01-02 18:31:30,148] - aiogram.dispatcher - Polling stopped for bot @free_listening_marathon_bot id=7531140107 - 'FREE LISTENING MARATHON'
dispatcher.py:554 #INFO     [2025-01-02 18:31:30,148] - aiogram.dispatcher - Polling stopped
client.py:22 #INFO     [2025-01-02 18:31:30,399] - config.logger - Connection to SQLite closed!
main.py:10 #INFO     [2025-01-02 18:31:32,474] - config.logger - Starting bot
client.py:15 #INFO     [2025-01-02 18:31:33,192] - config.logger - Successfully connected to the SQLite database!
client.py:45 #ERROR    [2025-01-02 18:31:33,192] - config.logger - SQLite error: table users already exists
dispatcher.py:527 #INFO     [2025-01-02 18:31:33,345] - aiogram.dispatcher - Start polling
dispatcher.py:341 #INFO     [2025-01-02 18:31:33,507] - aiogram.dispatcher - Run polling for bot @free_listening_marathon_bot id=7531140107 - 'FREE LISTENING MARATHON'
subscription.py:30 #INFO     [2025-01-02 18:31:35,044] - config.logger - USER: 1856563190, Azizbek Qodirov
subscription.py:50 #WARNING  [2025-01-02 18:31:35,576] - config.logger - Error checking channel jasurbekisaev: Telegram server says - Bad Request: member list is inaccessible
dispatcher.py:172 #INFO     [2025-01-02 18:31:36,202] - aiogram.event - Update id=475191436 is handled. Duration 1159 ms by bot id=7531140107
subscription.py:30 #INFO     [2025-01-02 18:31:52,561] - config.logger - USER: 1856563190, Azizbek Qodirov
subscription.py:50 #WARNING  [2025-01-02 18:31:53,004] - config.logger - Error checking channel jasurbekisaev: Telegram server says - Bad Request: member list is inaccessible
dispatcher.py:172 #INFO     [2025-01-02 18:31:53,191] - aiogram.event - Update id=475191437 is handled. Duration 633 ms by bot id=7531140107
dispatcher.py:172 #INFO     [2025-01-02 18:31:55,062] - aiogram.event - Update id=475191438 is handled. Duration 172 ms by bot id=7531140107
dispatcher.py:455 #WARNING  [2025-01-02 18:32:28,281] - aiogram.dispatcher - Received SIGINT signal
dispatcher.py:359 #INFO     [2025-01-02 18:32:28,281] - aiogram.dispatcher - Polling stopped for bot @free_listening_marathon_bot id=7531140107 - 'FREE LISTENING MARATHON'
dispatcher.py:554 #INFO     [2025-01-02 18:32:28,281] - aiogram.dispatcher - Polling stopped
client.py:22 #INFO     [2025-01-02 18:32:28,533] - config.logger - Connection to SQLite closed!
